<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-AIR8I1F" failures="1" tests="4" name="Default test(failed)" time="17.569" errors="0" timestamp="2020-10-28T12:36:21 IST">
  <testcase classname="TestRunner.RunTest" name="three" time="0.015">
    <skipped/>
  </testcase> <!-- three -->
  <testcase classname="TestRunner.RunTest" name="three" time="0.003">
    <skipped/>
  </testcase> <!-- three -->
  <testcase classname="TestRunner.RunTest" name="three" time="0.002">
    <skipped/>
  </testcase> <!-- three -->
  <testcase classname="TestRunner.RunTest" name="three" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestRunner.RunTest.three(RunTest.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- three -->
  <testcase classname="TestRunner.RunTest" name="launchwebsite" time="0.0">
    <ignored/>
  </testcase> <!-- launchwebsite -->
  <testcase classname="TestRunner.RunTest" name="verify_tabs_text" time="0.0">
    <ignored/>
  </testcase> <!-- verify_tabs_text -->
</testsuite> <!-- Default test(failed) -->
